/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: control.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export class ControlEvent extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        at?: dependency_1.google.protobuf.Timestamp;
        x?: number;
        y?: number;
        throtle?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("at" in data && data.at != undefined) {
                this.at = data.at;
            }
            if ("x" in data && data.x != undefined) {
                this.x = data.x;
            }
            if ("y" in data && data.y != undefined) {
                this.y = data.y;
            }
            if ("throtle" in data && data.throtle != undefined) {
                this.throtle = data.throtle;
            }
        }
    }
    get at() {
        return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 1) as dependency_1.google.protobuf.Timestamp;
    }
    set at(value: dependency_1.google.protobuf.Timestamp) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_at() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get x() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set x(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    get y() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set y(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get throtle() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set throtle(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        x?: number;
        y?: number;
        throtle?: number;
    }): ControlEvent {
        const message = new ControlEvent({});
        if (data.at != null) {
            message.at = dependency_1.google.protobuf.Timestamp.fromObject(data.at);
        }
        if (data.x != null) {
            message.x = data.x;
        }
        if (data.y != null) {
            message.y = data.y;
        }
        if (data.throtle != null) {
            message.throtle = data.throtle;
        }
        return message;
    }
    toObject() {
        const data: {
            at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            x?: number;
            y?: number;
            throtle?: number;
        } = {};
        if (this.at != null) {
            data.at = this.at.toObject();
        }
        if (this.x != null) {
            data.x = this.x;
        }
        if (this.y != null) {
            data.y = this.y;
        }
        if (this.throtle != null) {
            data.throtle = this.throtle;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_at)
            writer.writeMessage(1, this.at, () => this.at.serialize(writer));
        if (this.x != 0)
            writer.writeInt32(2, this.x);
        if (this.y != 0)
            writer.writeInt32(3, this.y);
        if (this.throtle != 0)
            writer.writeInt32(4, this.throtle);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ControlEvent {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ControlEvent();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.at, () => message.at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                    break;
                case 2:
                    message.x = reader.readInt32();
                    break;
                case 3:
                    message.y = reader.readInt32();
                    break;
                case 4:
                    message.throtle = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static override deserializeBinary(bytes: Uint8Array): ControlEvent {
        return ControlEvent.deserialize(bytes);
    }
}
