/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: msg_header.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum MsgHeader {
    CONTROL_EVENT = 0,
    VIDEO_ANALYSIS_FACES = 1
}
