apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  type: NodePort
  ports:
    - name: "30000"
      port: 30000
      protocol: UDP
      targetPort: 3478
      nodePort: 30000 
    - name: 30000-tcp
      port: 30000
      targetPort: 3478
      nodePort: 30000
    - name: "31000"
      port: 31000
      protocol: UDP
      targetPort: 31000
      nodePort: 31000
    - name: "31001"
      port: 31001
      protocol: UDP
      targetPort: 31001
      nodePort: 31001
    - name: "31002"
      port: 31002
      protocol: UDP
      targetPort: 31002
      nodePort: 31002
    - name: "31003"
      port: 31003
      protocol: UDP
      targetPort: 31003
      nodePort: 31003
  selector:
    io.kompose.service: coturn
