apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coturn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: coturn
    spec:
      containers:
        - args:
            - -n
            - --log-file=stdout
            - --min-port=49160
            - --max-port=49200
            - --realm=cars.growbe.ca
            - --external-ip=216.209.231.236
          image: instrumentisto/coturn
          name: coturn
          ports:
            - containerPort: 3478
              protocol: UDP
            - containerPort: 3478
            - containerPort: 49160
              protocol: UDP
            - containerPort: 49161
              protocol: UDP
            - containerPort: 49162
              protocol: UDP
            - containerPort: 49163
              protocol: UDP
            - containerPort: 49164
              protocol: UDP
            - containerPort: 49165
              protocol: UDP
            - containerPort: 49166
              protocol: UDP
            - containerPort: 49167
              protocol: UDP
            - containerPort: 49168
              protocol: UDP
            - containerPort: 49169
              protocol: UDP
            - containerPort: 49170
              protocol: UDP
            - containerPort: 49171
              protocol: UDP
            - containerPort: 49172
              protocol: UDP
            - containerPort: 49173
              protocol: UDP
            - containerPort: 49174
              protocol: UDP
            - containerPort: 49175
              protocol: UDP
            - containerPort: 49176
              protocol: UDP
            - containerPort: 49177
              protocol: UDP
            - containerPort: 49178
              protocol: UDP
            - containerPort: 49179
              protocol: UDP
            - containerPort: 49180
              protocol: UDP
            - containerPort: 49181
              protocol: UDP
            - containerPort: 49182
              protocol: UDP
            - containerPort: 49183
              protocol: UDP
            - containerPort: 49184
              protocol: UDP
            - containerPort: 49185
              protocol: UDP
            - containerPort: 49186
              protocol: UDP
            - containerPort: 49187
              protocol: UDP
            - containerPort: 49188
              protocol: UDP
            - containerPort: 49189
              protocol: UDP
            - containerPort: 49190
              protocol: UDP
            - containerPort: 49191
              protocol: UDP
            - containerPort: 49192
              protocol: UDP
            - containerPort: 49193
              protocol: UDP
            - containerPort: 49194
              protocol: UDP
            - containerPort: 49195
              protocol: UDP
            - containerPort: 49196
              protocol: UDP
            - containerPort: 49197
              protocol: UDP
            - containerPort: 49198
              protocol: UDP
            - containerPort: 49199
              protocol: UDP
            - containerPort: 49200
              protocol: UDP
          resources: {}
      restartPolicy: Always
status: {}
