apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  type: NodePort
  ports:
    - name: "3478"
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: 3478-tcp
      port: 3478
      targetPort: 3478
    - name: "49160"
      port: 49160
      protocol: UDP
      targetPort: 49160
    - name: "49161"
      port: 49161
      protocol: UDP
      targetPort: 49161
    - name: "49162"
      port: 49162
      protocol: UDP
      targetPort: 49162
    - name: "49163"
      port: 49163
      protocol: UDP
      targetPort: 49163
    - name: "49164"
      port: 49164
      protocol: UDP
      targetPort: 49164
    - name: "49165"
      port: 49165
      protocol: UDP
      targetPort: 49165
    - name: "49166"
      port: 49166
      protocol: UDP
      targetPort: 49166
    - name: "49167"
      port: 49167
      protocol: UDP
      targetPort: 49167
    - name: "49168"
      port: 49168
      protocol: UDP
      targetPort: 49168
    - name: "49169"
      port: 49169
      protocol: UDP
      targetPort: 49169
    - name: "49170"
      port: 49170
      protocol: UDP
      targetPort: 49170
    - name: "49171"
      port: 49171
      protocol: UDP
      targetPort: 49171
    - name: "49172"
      port: 49172
      protocol: UDP
      targetPort: 49172
    - name: "49173"
      port: 49173
      protocol: UDP
      targetPort: 49173
    - name: "49174"
      port: 49174
      protocol: UDP
      targetPort: 49174
    - name: "49175"
      port: 49175
      protocol: UDP
      targetPort: 49175
    - name: "49176"
      port: 49176
      protocol: UDP
      targetPort: 49176
    - name: "49177"
      port: 49177
      protocol: UDP
      targetPort: 49177
    - name: "49178"
      port: 49178
      protocol: UDP
      targetPort: 49178
    - name: "49179"
      port: 49179
      protocol: UDP
      targetPort: 49179
    - name: "49180"
      port: 49180
      protocol: UDP
      targetPort: 49180
    - name: "49181"
      port: 49181
      protocol: UDP
      targetPort: 49181
    - name: "49182"
      port: 49182
      protocol: UDP
      targetPort: 49182
    - name: "49183"
      port: 49183
      protocol: UDP
      targetPort: 49183
    - name: "49184"
      port: 49184
      protocol: UDP
      targetPort: 49184
    - name: "49185"
      port: 49185
      protocol: UDP
      targetPort: 49185
    - name: "49186"
      port: 49186
      protocol: UDP
      targetPort: 49186
    - name: "49187"
      port: 49187
      protocol: UDP
      targetPort: 49187
    - name: "49188"
      port: 49188
      protocol: UDP
      targetPort: 49188
    - name: "49189"
      port: 49189
      protocol: UDP
      targetPort: 49189
    - name: "49190"
      port: 49190
      protocol: UDP
      targetPort: 49190
    - name: "49191"
      port: 49191
      protocol: UDP
      targetPort: 49191
    - name: "49192"
      port: 49192
      protocol: UDP
      targetPort: 49192
    - name: "49193"
      port: 49193
      protocol: UDP
      targetPort: 49193
    - name: "49194"
      port: 49194
      protocol: UDP
      targetPort: 49194
    - name: "49195"
      port: 49195
      protocol: UDP
      targetPort: 49195
    - name: "49196"
      port: 49196
      protocol: UDP
      targetPort: 49196
    - name: "49197"
      port: 49197
      protocol: UDP
      targetPort: 49197
    - name: "49198"
      port: 49198
      protocol: UDP
      targetPort: 49198
    - name: "49199"
      port: 49199
      protocol: UDP
      targetPort: 49199
    - name: "49200"
      port: 49200
      protocol: UDP
      targetPort: 49200
  selector:
    io.kompose.service: coturn
