apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress-2
  annotations:
    cert-manager.io/issuer: issuer-do
    nginx.org/websocket-services: "signaling-server"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
spec:
  tls:
  - hosts:
    - cars.growbe.ca
    - signaling.cars.growbe.ca
    secretName: tls-quintal 
  rules:
  - host: cars.growbe.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui 
            port:
              number: 8080
  - host: signaling.cars.growbe.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: signaling-server
            port:
              number: 8000