apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - image: ghcr.io/berlingoqc/quintal/ui:latest
          name: ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
      - name: ghcr
      restartPolicy: Always
status: {}
