# Simple workflow for deploying static content to GitHub Pages
name: Build on main

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
jobs:
  # Single deploy job since we're just deploying
  app_release:
    runs-on: ubuntu-latest
    container: ghcr.io/berlingoqc/quintal/crossbuild:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build linux arm64
        run: ''
      - name: Build linux armvf
        run: ''
